---
title: "Subsetting Notes"
output: html_document
---

## Atomic Vectors


```{r}
x <- c(2.1, 4.2, 3.3, 5.4)

# Positive integers return elements at specified position
x[c(3, 1)]
x[c(1, 1)]

# Negative integers ommit
x[-c(3, 1)]

# Logical vectors select elements corresponding to TRUE
# vector is recycled if too short
# missing value returns missing value
x[c(TRUE, TRUE, FALSE, NA)]

# nothing returns origional vector
x[]

# zero returns a zero length vector
x[0]

# if named, can use character vectors

y <- setNames(x, letters[1:4])
y[c('a', 'a', 'b')]
```

## Lists

[ returns a list, [[ and $ return components of lists

## Matrices and Arrays

Can subset higher dimensional structures with multiple vectors, with single vectors and with a matrix

```{r}
a <- matrix(1:9, nrow = 3)
colnames(a) <- c("A", "B", "C")

a[1:2, ]
a[c(T,F,T), c("B", "A")]
a[0, -2]
```

## Data Frames

```{r}
df <- data.frame(x = 1:3, y = 3:1, z = letters[1:3])
df[df$x == 2, ]
df[c(1,3), ]

# Notes can subset like a list or like a matrix. Matrix
# simplifies by default, list subsetting does not
df[c("x", "z")]
df[, c("x", "z")]

```
